env:
  global:
    - CC_TEST_REPORTER_ID=ABC123

language: node_js

node_js:
  - "stable"

services:
  - postgresql

before_install:
  - npm install sequelize-cli -g
   

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm add sequelize-cli
  - psql -c 'drop database if exists test_database;' -U postgres
  - psql -c 'create database test_database;' -U postgres
  - npm run migration

script:
  - bundle exec rspec
  - npm run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
  - npm run coveralls