language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

addons:
  postgresql: "9.6"


install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
 

after_success:
  - npm run coverage
