
language: node_js

node_js:
 - "stable"

services:
 - postgresql

before_install:
 - npm install sequelize-cli -g
   

before-script:
 - npm add sequelize-cli

before_script:
 - psql -c 'drop database if exists test_database;' -U postgres
 - psql -c 'create database test_database;' -U postgres
 - npm run migration

script:
 - npm run test

after_success:
 - npm run coveralls