
language: node_js

node_js:
 - "stable"

services:
 - postgresql

before_install:
 - npm install sequelize-cli -g

env:
 global:
   - TEST_DATABASE_URL=postgres://postgres:@127.0.0.1:5432/test_database
   - SECRET_KEY=secretkey
   - NODE_ENV=test
   - SOCKET_PORT=3000

before-script:
 - npm add sequelize-cli

before_script:
 - psql -c 'drop database if exists test_database;' -U postgres
 - psql -c 'create database test_database;' -U postgres
 - npm run migration

script:
 - npm run test

after_success:
 - npm run coveralls